version: '3.8'

services:
  postgres:
    restart: always
    container_name: "${POSTGRES_NAME}"
    image: "postgres:15"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard_mqtt_broker
      POSTGRES_PASSWORD: postgres
    volumes:
      - tbmq-postgres-data:/var/lib/postgresql/data
  kafka:
    restart: always
    container_name: "${KAFKA_NAME}"
    image: "bitnami/kafka:3.5.1"
    ports:
      - "9092"
    env_file:
      - kafka.env
    volumes:
      - tbmq-kafka-data:/bitnami/kafka
  tbmq1:
    restart: always
    container_name: "${TBMQ_1_NAME}"
    image: "${DOCKER_REPO}/${DOCKER_NAME}:${TBMQ_VERSION}"
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tbmq1
      #JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-mqtt-broker.env
    volumes:
      - tbmq-config:/config
      - tbmq1-logs:/var/log/thingsboard-mqtt-broker
    depends_on:
      - postgres
      - kafka

  # nginx:
  #   image: openresty/openresty:latest
  #   container_name: nginx-proxy
  #   volumes:
  #     - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
  #     - ./verify.lua:/usr/local/openresty/nginx/verify.lua:ro
  #   ports:
  #     - "1884:1884" # Port for MQTT clients to connect through proxy
  #   depends_on:
  #     - tbmq1


volumes:
  tbmq-postgres-data:
    #external: true
  tbmq-kafka-data:
    #external: true
  tbmq1-logs:
    #external: true
  tbmq-config:
    #external: true
#
# Copyright ©️ 2016-2024 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# version: "3.0"
# services:
#  postgres:
#    restart: always
#    image: "postgres:15"
#    ports:
#      - "5432"
#    environment:
#      POSTGRES_DB: thingsboard_mqtt_broker
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - tbmq-postgres-data:/var/lib/postgresql/data
#  kafka:
#    restart: always
#    image: "bitnami/kafka:3.5.1"
#    ports:
#      - "9092"
#    environment:
#      KAFKA_CFG_NODE_ID: 0
#      KAFKA_CFG_PROCESS_ROLES: controller,broker
#      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
#      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
#      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#    volumes:
#      - tbmq-kafka-data:/bitnami/kafka
#  tbmq:
#    restart: always
#    image: "thingsboard/tbmq:1.3.0"
#    depends_on:
#      - postgres
#      - kafka
#    ports:
#      - "8083:8083"
#      - "1883:1883"
#      - "8084:8084"
#      - "8883:8883"
#    environment:
#      TB_SERVICE_ID: tbmq
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard_mqtt_broker
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      TB_KAFKA_SERVERS: kafka:9092
# #      LISTENER_SSL_ENABLED: true
#      SECURITY_MQTT_AUTH_STRATEGY: SINGLE
#      SECURITY_MQTT_SSL_ENABLED: true
#      SECURITY_MQTT_BASIC_ENABLED: true
#      LISTENER_SSL_PEM_CERT: "serverCert.pem"
#      LISTENER_SSL_PEM_KEY: "server_key.pem"
#      # MQTT_SSL_SKIP_VALIDITY_CHECK_FOR_CLIENT_CERT: true
#      # LISTENER_SSL_PEM_KEY_PASSWORD: "3108" # Only if your key is password protected
#      # MQTT_SSL_PEM_CA_CERT: "./certificates//ca.crt"
#      #JAVA_OPTS: "-Xmx2048M -Xms2048M -Xss384k -XX:+AlwaysPreTouch"
#    volumes:
#      - tbmq-logs:/var/log/thingsboard-mqtt-broker
#      - tbmq-data:/data

# volumes:
#  tbmq-postgres-data:
#    external: true
#  tbmq-kafka-data:
#    external: true
#  tbmq-logs:
#    external: true
#  tbmq-data:
#    external: true
# #
#
#
#
# Copyright ©️ 2016-2024 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# services:
#   postgres:
#     restart: always
#     image: "postgres:15"
#     ports:
#       - "5432"
#     environment:
#       POSTGRES_DB: thingsboard_mqtt_broker
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - tbmq-postgres-data:/var/lib/postgresql/data
#   kafka:
#     restart: always
#     image: "bitnami/kafka:3.5.1"
#     ports:
#       - "9092"
#     environment:
#       KAFKA_CFG_NODE_ID: 0
#       KAFKA_CFG_PROCESS_ROLES: controller,broker
#       KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
#       KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#       KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
#       KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#       KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#     volumes:
#       - tbmq-kafka-data:/bitnami/kafka
#   redis:
#     restart: always
#     image: "bitnami/redis:7.0"
#     environment:
#       # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       ALLOW_EMPTY_PASSWORD: "yes"
#     ports:
#       - "6379"
#     volumes:
#       - tbmq-redis-data:/bitnami/redis/data
#   tbmq:
#     restart: always
#     image: "thingsboard/tbmq:1.4.0"
#     depends_on:
#       - postgres
#       - kafka
#       - redis
#     ports:
#       - "8083:8083"
#       - "1883:1883"
#       - "8084:8084"
#       - "8883:8883"
#     environment:
#       TB_SERVICE_ID: tbmq
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard_mqtt_broker
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: postgres
#       TB_KAFKA_SERVERS: kafka:9092
#       REDIS_HOST: redis
#       SECURITY_MQTT_BASIC_ENABLED: true
#       SECURITY_MQTT_SSL_ENABLED: true
#       LISTENER_SSL_ENABLED: true
#       LISTENER_SSL_BIND_PORT: 8883
#       LISTENER_SSL_PEM_CERT: "/http-config/server.pem"
#       LISTENER_SSL_PEM_KEY: "/http-config/server_Key.pem"
#       SECURITY_MQTT_AUTH_STRATEGY: SINGLE



#       #JAVA_OPTS: "-Xmx2048M -Xms2048M -Xss384k -XX:+AlwaysPreTouch"
#     volumes:
#       - tbmq-logs:/var/log/thingsboard-mqtt-broker
#       - tbmq-data:/data
#       - /Users/mbharani/TBMQ-MQTT-Websocket/final_cert:/http-config

# volumes:
#   tbmq-postgres-data:
#     external: true
#   tbmq-kafka-data:
#     external: true
#   tbmq-redis-data:
#     external: true
#   tbmq-logs:
#     external: true
#   tbmq-data:
#     external: true
