export const POST_LOGIN_DETAILS = 'POST_LOGIN_DETAILS';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
export const POST_SIGNUP_DETAILS = 'POST_SIGNUP_DETAILS';